name: Test PHP
on:
  push:
    branches-ignore:
      - staging
      - production
    paths:
      - '**.php'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Shutdown default MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setting MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql root password: "password"
          mysql database: "application"
      - name: Waiting for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=test --silent --show-warnings=FALSE; do
            sleep 1
          done
      - name: Environment
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run phpunit
        run: vendor/bin/phpunit --color=always --testdox --coverage-text --coverage-html coverage/ -c tests/php/phpunit.xml

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-html
          path: coverage/


